insert into public.menu_items (item_key,type,section_id,section_title,name,description,volume,price,image_url,available,sort_order) values
('bar:vdsiob-uwa:coca-cola','bar','vdsiob-uwa','Напитки','Coca-Cola','Coca-Cola – один из самых популярных безалкогольных напитков в истории, а также один из наиболее узнаваемых брендов в мире.','',400,'/menu-images/product-vdsiob-uwa-mhgrmxshtn.webp',true,0),
('bar:vdsiob-uwa:coca-cola-zero','bar','vdsiob-uwa','Напитки','Coca-Cola zero','Coca-Cola Zero – это возможность насладиться удивительно освежающим вкусом классической Coca-Cola, не задумываясь о калориях. Coca-Cola Zero - отличный вкус без сахара и калорий!','',400,'/menu-images/product-vdsiob-uwa-uc-cornwht.webp',true,1),
('bar:vdsiob-uwa:fanta','bar','vdsiob-uwa','Напитки','Fanta','Fanta Апельсин – это классический безалкогольный напиток с легким фруктовым вкусом, содержащий 3% натурального апельсинового сока.','',400,'/menu-images/product-vdsiob-uwa-knhsikzxju.webp',true,2),
('bar:vdsiob-uwa:тоник','bar','vdsiob-uwa','Напитки','Тоник','','',350,'/menu-images/product-vdsiob-uwa-oxxjdgwwxv.webp',true,3),
('bar:vdsiob-uwa:dr-pepper','bar','vdsiob-uwa','Напитки','Dr Pepper','Освежающий безалкогольный сильногазированный пастеризованный напиток Dr Pepper Regular (Classic). Dr Pepper Classic представляет собой уникальное сочетание 23 различных оттенков вкуса (амаретто, миндаль, ежевика, чёрная солодка, морковь, гвоздика, вишня, карамель, кола, имбирь, можжевельник, лимон, патока, мускатный орех, апельсин, чернослив, слива, перец, ром, малина, помидоры, ваниль и секретный ингредиент производителя).','',350,'/menu-images/product-vdsiob-uwa-hdtpod-xyw.webp',true,4),
('bar:vdsiob-uwa:пепси','bar','vdsiob-uwa','Напитки','Пепси','','',350,'/menu-images/product-vdsiob-uwa-qhdtdmtiol.webp',true,5),
('bar:vdsiob-uwa:red-bull','bar','vdsiob-uwa','Напитки','Red bull','Red Bull Energy Drink — безалкогольный энергетический газированный напиток. 
Энергетические напитки Red Bull содержат ингредиенты высокого качества: кофеин, таурин, витамины B, сахар и воду из альпийских регионов. В одной банке 250 мл содержится столько же кофеина, сколько в чашке кофе такого же объема.','',450,'/menu-images/product-vdsiob-uwa-ctxycxeiaj.webp',true,6),
('bar:vdsiob-uwa:red-bull-sugarfree','bar','vdsiob-uwa','Напитки','Red bull sugarfree','Red Bull Sugarfree — безалкогольный тонизирующий газированный напиток без сахара.','',450,'/menu-images/product-vdsiob-uwa-rmyicokztj.webp',true,7),
('bar:vdsiob-uwa:сок-в-ассортименте','bar','vdsiob-uwa','Напитки','Сок в ассортименте','','',350,'/menu-images/product-vdsiob-uwa-a-vevanmfa.webp',true,8),
('bar:vdsiob-uwa:лаймон-фреш','bar','vdsiob-uwa','Напитки','Лаймон фреш','','',200,'/menu-images/product-vdsiob-uwa-ptvdfv-pmf.webp',true,9),
('bar:vdsiob-uwa:вода-без-газа','bar','vdsiob-uwa','Напитки','Вода без газа','Природная минеральная столовая вода обладает сбалансированным вкусом. Уникальный полноценный состав воды включает в себя микроэлементы и минералы, необходимые для поддержки здоровья. Вода Mever рекомендована для ежедневного употребления.','',300,'/menu-images/product-vdsiob-uwa-jhdqwoslzx.webp',true,10),
('bar:vdsiob-uwa:вода-с-газом','bar','vdsiob-uwa','Напитки','Вода с газом','Borjomi — легендарная вода, которой больше 130 лет, ее знают и любят миллионы людей по всему миру. Она зарождается в вулканических глубинах Грузии в экологически чистой долине «Боржоми» и благодаря сочетанию полезных свойств вулканической воды и заряжающей силой минералов и микроэлементов Borjomi заботится о вашем здоровье, а узнаваемый с первого глотка вкус придает силы на новые свершения и идеи!','',450,'/menu-images/product-vdsiob-uwa-j-nojqhwzw.webp',true,11),
('bar:vdsiob-uwa:авторские-лимонады-в-ассортименте','bar','vdsiob-uwa','Напитки','Авторские лимонады в ассортименте','Лимонад - один из любимейших прохладительных напитков, вкус которого мы узнаём с детства.','',990,'/menu-images/product-vdsiob-uwa-vsncndtncz.webp',true,12),
('bar:vdsiob-uwa:авторские-лимонады-0-5','bar','vdsiob-uwa','Напитки','Авторские лимонады 0,5','','',490,'/menu-images/product-vdsiob-uwa-wtzk-rcgnz.webp',true,13),
('bar:vdsiob-uwa:безалкогольные-коктейли-в-ассортименте','bar','vdsiob-uwa','Напитки','Безалкогольные коктейли в ассортименте','','',690,'/menu-images/product-vdsiob-uwa-tjpgcveevb.webp',true,14),
('bar:tpzfbqwhfe:китайский-бай-му-дань-900мл','bar','tpzfbqwhfe','Чайная карта','Китайский Бай му Дань 900мл.','','',1000,'/menu-images/product-tpzfbqwhfe-itcrmerupz.webp',true,15),
('bar:tpzfbqwhfe:китайский-да-хун-пао-900мл','bar','tpzfbqwhfe','Чайная карта','Китайский Да Хун Пао 900мл.','','',1000,'/menu-images/product-tpzfbqwhfe-gkgfalbyig.webp',true,16),
('bar:tpzfbqwhfe:китайский-габа-900мл','bar','tpzfbqwhfe','Чайная карта','Китайский Габа 900мл.','','',1000,'/menu-images/product-tpzfbqwhfe-cecpsefjqg.webp',true,17),
('bar:tpzfbqwhfe:гречишный-900-мл','bar','tpzfbqwhfe','Чайная карта','Гречишный 900 мл.','','',1000,'/menu-images/product-tpzfbqwhfe-tgcnbjbscl.webp',true,18),
('bar:tpzfbqwhfe:те-гуань-инь-900мл','bar','tpzfbqwhfe','Чайная карта','Те гуань инь 900мл','Тегуаньинь обладает свежим, ненавязчивым вкусом и завораживающим ароматом. Он очень яркий и запоминающийся. В аромате вы можете почувствовать свежесть, легкость и ноты цветущей сирени.','',1000,'/menu-images/product-tpzfbqwhfe-zlbqveydkl.webp',true,19),
('bar:tpzfbqwhfe:молочный-улун-900мл','bar','tpzfbqwhfe','Чайная карта','Молочный улун 900мл','Молочный улун – один из самых популярных сортов улуна в мире. Его любят за яркий и легкий сливочный вкус, тонизирующий эффект и полезные для организма свойства','',700,'/menu-images/product-tpzfbqwhfe-mxdn-vuuaq.webp',true,20),
('bar:tpzfbqwhfe:сенча-900мл','bar','tpzfbqwhfe','Чайная карта','Сенча 900мл','Сенча – классический китайский зеленый чай, обладающий сладковатым, чуть вяжущим вкусом и нежным свежим ароматом.','',700,'/menu-images/product-tpzfbqwhfe-jheaatvkov.webp',true,21),
('bar:tpzfbqwhfe:жасминовый-900мл','bar','tpzfbqwhfe','Чайная карта','Жасминовый 900мл','Среди его особенностей значится тонкий аромат и нежный, гармоничный вкус. Узбекский зеленый чай – один из лучших чаев в мире.','',700,'/menu-images/product-tpzfbqwhfe-qvzavydwoq.webp',true,22),
('bar:tpzfbqwhfe:ассам-900мл','bar','tpzfbqwhfe','Чайная карта','Ассам 900мл','Ассам богат антиоксидантами, замедляющими процессы старения и предотвращающими развитие хронических заболеваний сердечно-сосудистой системы.','',700,'/menu-images/product-tpzfbqwhfe-kxeivklqqe.webp',true,23),
('bar:tpzfbqwhfe:наглый-фрукт-900мл','bar','tpzfbqwhfe','Чайная карта','Наглый фрукт 900мл','Насыщенный дерзкий вкус, ярко-фруктовый, кисловатый, с горчинкой.','',700,'/menu-images/product-tpzfbqwhfe-n-bkxhcj-x.webp',true,24),
('bar:tpzfbqwhfe:здоровый-сон-900мл','bar','tpzfbqwhfe','Чайная карта','Здоровый сон 900мл','Напиток чайный Здоровый сон – вкусный и полезный напиток, который поможет вам расслабиться, забыть о насущных проблемах и подготовиться ко сну.','',700,'/menu-images/product-tpzfbqwhfe-zzweqbyzsh.webp',true,25),
('bar:tpzfbqwhfe:пуэр-900мл','bar','tpzfbqwhfe','Чайная карта','Пуэр 900мл','Пуэр — уникальный постферментированный чай, выращенный в провинции Юннань, Китай.','',700,'/menu-images/product-tpzfbqwhfe--pcotmbyjw.webp',true,26),
('bar:vgejqoyhou:лимон','bar','vgejqoyhou','Добавки к чаю','Лимон','','',100,'/menu-images/product-vgejqoyhou-iybdegirxs.webp',true,27),
('bar:vgejqoyhou:мята','bar','vgejqoyhou','Добавки к чаю','Мята','','',100,'/menu-images/product-vgejqoyhou-glpe-vzjvz.webp',true,28),
('bar:vgejqoyhou:чабрец','bar','vgejqoyhou','Добавки к чаю','Чабрец','','',100,'/menu-images/product-vgejqoyhou-pyipykylgy.webp',true,29),
('bar:vgejqoyhou:м-д','bar','vgejqoyhou','Добавки к чаю','Мёд','','',100,'/menu-images/product-vgejqoyhou-fxoqs-gurk.webp',true,30),
('bar:bjhbvwhhq-:манго-маракуйя','bar','bjhbvwhhq-','Нечайный чай','Манго-маракуйя','Крафтовый чай с приятным освежающим вкусом, дополненный непревзойденным ароматом тропических фруктов.','',900,'/menu-images/product-bjhbvwhhq--vypdtrsdww.webp',true,31),
('bar:bjhbvwhhq-:малина-черная-смородина','bar','bjhbvwhhq-','Нечайный чай','Малина - черная смородина','Один из лучших согревающих миксов с полезными свойствами.','',900,'/menu-images/product-bjhbvwhhq--xvqsozmapn.webp',true,32),
('bar:bjhbvwhhq-:персиковый','bar','bjhbvwhhq-','Нечайный чай','Персиковый','Чай который очень полюбили наши гости.','',900,'/menu-images/product-bjhbvwhhq--coxaivh-qx.webp',true,33),
('bar:bjhbvwhhq-:облепиховый','bar','bjhbvwhhq-','Нечайный чай','Облепиховый','Облепиховый чай - настоящая находка для уставшего, испытывающего недостаток витаминов организма.','',900,'/menu-images/product-bjhbvwhhq--mpgpdtgitf.webp',true,34),
('bar:bjhbvwhhq-:малина-пан','bar','bjhbvwhhq-','Нечайный чай','Малина-Пан','','',900,'/menu-images/product-bjhbvwhhq--zdwyugkwfz.webp',true,35),
('bar:bjhbvwhhq-:инжир-чабрец','bar','bjhbvwhhq-','Нечайный чай','Инжир-Чабрец','','',900,'/menu-images/product-bjhbvwhhq--tuaumtncex.webp',true,36),
('bar:bjhbvwhhq-:черемуха-личи','bar','bjhbvwhhq-','Нечайный чай','Черемуха-Личи','','',900,'/menu-images/product-bjhbvwhhq--uohlhpnjel.webp',true,37),
('bar:jlabxgucjm:эспрессо','bar','jlabxgucjm','Кофе','Эспрессо','Эспрессо – это, действительно, прекрасный способ оживить унылый день.','',200,'/menu-images/product-jlabxgucjm-jwa-tuemaf.webp',true,38),
('bar:jlabxgucjm:американо','bar','jlabxgucjm','Кофе','Американо','Американо - кофе эспрессо, дополнительно разбавленный водой.','',200,'/menu-images/product-jlabxgucjm-pomutgxcxp.webp',true,39),
('bar:jlabxgucjm:капучино','bar','jlabxgucjm','Кофе','Капучино','','',350,'/menu-images/product-jlabxgucjm-ugjuwlsiwr.webp',true,40),
('bar:jlabxgucjm:латте','bar','jlabxgucjm','Кофе','Латте','','',350,'/menu-images/product-jlabxgucjm-obl-khuswc.webp',true,41),
('bar:uhomlq-uur:hofbrau','bar','uhomlq-uur','Пиво и сидр','Hofbrau','Hofbräu — это натуральный продукт, который готовится в соответствии с "Законом о чистоте пива" 1516 года. Производитель пристально следит за качеством сырья и за процессом его использования. Каждый из четырех компонентов пенного напитка имеет особое значение в его производстве.','',850,'/menu-images/product-uhomlq-uur-kyutnhhiih.webp',true,42),
('bar:uhomlq-uur:paulaner','bar','uhomlq-uur','Пиво и сидр','Paulaner','Это мягкое золотистое пиво, имеющее приятный солодовый вкус с тонкими нотками хмеля. Полнотелое, янтарного цвета, приготовленное методом низового брожения.','',750,'/menu-images/product-uhomlq-uur-kpgzutapfx.webp',true,43),
('bar:uhomlq-uur:guinness','bar','uhomlq-uur','Пиво и сидр','Guinness','Пиво Guinness обладает солодовой сладостью и хмелевой горечью с нотками кофе и шоколада.','',750,'/menu-images/product-uhomlq-uur-uqnragypsf.webp',true,44),
('bar:uhomlq-uur:spaten','bar','uhomlq-uur','Пиво и сидр','Spaten','Пиво Шпатен отличается образцовым золотистым цветом, а при наливании дает идеально белую бархатистую пенную шапку. В аромате напитка хорошо ощущается хмель и солод, которые дополнены штрихами луговой травы.','',700,'/menu-images/product-uhomlq-uur-nawhirmlfq.webp',true,45),
('bar:uhomlq-uur:corona-extra','bar','uhomlq-uur','Пиво и сидр','Corona Extra','"Корона Экстра" — напиток с элегантным, освежающим вкусом, в котором раскрываются нотки солода, молодой кукурузы и лайма.','',500,'/menu-images/product-uhomlq-uur-lqhosurygu.webp',true,46),
('bar:uhomlq-uur:циндао','bar','uhomlq-uur','Пиво и сидр','Циндао','','',500,'/menu-images/product-uhomlq-uur-zdzbqhxdne.webp',true,47),
('bar:uhomlq-uur:clausthaller','bar','uhomlq-uur','Пиво и сидр','Clausthaller','Clausthaler (Клаусталер) - премиальное безалкогольное пиво из Германии, обладающее безупречным вкусом и высочайшим качеством.','',550,'/menu-images/product-uhomlq-uur-uq-zdjeojk.webp',true,48),
('bar:uhomlq-uur:hoegarden','bar','uhomlq-uur','Пиво и сидр','Hoegarden','Хугарден (Hoegaarden) — название нефильтрованного пшеничного, то есть белого пива, которое производят в небольшой бельгийской деревеньке.','',450,'/menu-images/product-uhomlq-uur-ltivfj-gzt.webp',true,49),
('bar:uhomlq-uur:stella-artois','bar','uhomlq-uur','Пиво и сидр','Stella Artois','Stella Artois - суперпремиальный классический лагер с особым горьковатым вкусом и освежающим хмелевым послевкусием.','',500,'/menu-images/product-uhomlq-uur-dodncjwcgr.webp',true,50),
('bar:uhomlq-uur:bud','bar','uhomlq-uur','Пиво и сидр','BUD','','',400,'/menu-images/product-uhomlq-uur-mrg-fyrywz.webp',true,51),
('bar:uhomlq-uur:krusovice','bar','uhomlq-uur','Пиво и сидр','Krusovice','','',400,'/menu-images/product-uhomlq-uur-yxjwbuoghf.webp',true,52),
('bar:uhomlq-uur:сидр-в-ассортименте','bar','uhomlq-uur','Пиво и сидр','Сидр в ассортименте','','',400,'/menu-images/product-uhomlq-uur-hydjektbek.webp',true,53),
('bar:uhomlq-uur:сидр-0-7','bar','uhomlq-uur','Пиво и сидр','Сидр 0,7','','',900,'/menu-images/product-uhomlq-uur-ejjfvdjwci.webp',true,54),
('bar:mcwxofzjor:совиньон-блан-125-мл','bar','mcwxofzjor','Белые вина','Совиньон Блан 125 мл.','','',550,'/menu-images/product-mcwxofzjor-zylepimimb.webp',true,55),
('bar:mcwxofzjor:пино-гриджио-125-мл','bar','mcwxofzjor','Белые вина','Пино Гриджио 125 мл.','','',550,'/menu-images/product-mcwxofzjor-wvymwktgd.webp',true,56),
('bar:mcwxofzjor:рислинг-125-мл','bar','mcwxofzjor','Белые вина','Рислинг 125 мл.','','',500,'/menu-images/product-mcwxofzjor-h-mqdrgquu.webp',true,57),
('bar:mcwxofzjor:совиньон-блан-750-мл','bar','mcwxofzjor','Белые вина','Совиньон Блан 750 мл.','','',3300,'/menu-images/product-mcwxofzjor-dvxshhtzga.webp',true,58),
('bar:mcwxofzjor:пино-гриджио-750-мл','bar','mcwxofzjor','Белые вина','Пино Гриджио 750 мл.','','',3300,'/menu-images/product-mcwxofzjor-sgfyuq-xlc.webp',true,59),
('bar:mcwxofzjor:рислинг-750-мл','bar','mcwxofzjor','Белые вина','Рислинг 750 мл.','','',3000,'/menu-images/product-mcwxofzjor-fwvejaqdb.webp',true,60),
('bar:faebghfnif:каберне-совиньон-125-мл','bar','faebghfnif','Красные вина','Каберне Совиньон 125 мл.','','',550,'/menu-images/product-faebghfnif-febeketqup.webp',true,61),
('bar:faebghfnif:кьянти-125-мл','bar','faebghfnif','Красные вина','Кьянти 125 мл.','','',600,'/menu-images/product-faebghfnif-knxetqbkat.webp',true,62),
('bar:faebghfnif:мальбек-125-мл','bar','faebghfnif','Красные вина','Мальбек 125 мл.','','',650,'/menu-images/product-faebghfnif-hvxsmqargz.webp',true,63),
('bar:faebghfnif:каберне-совиньон-750-мл','bar','faebghfnif','Красные вина','Каберне Совиньон 750 мл.','','',3300,'/menu-images/product-faebghfnif-rvsrxztsyh.webp',true,64),
('bar:faebghfnif:кьянти-750-мл','bar','faebghfnif','Красные вина','Кьянти 750 мл.','','',3600,'/menu-images/product-faebghfnif-icfjcgwqfh.webp',true,65),
('bar:faebghfnif:мальбек-750-мл','bar','faebghfnif','Красные вина','Мальбек 750 мл.','','',3900,'/menu-images/product-faebghfnif-kpzksixqzo.webp',true,66),
('bar:ckwsbynkaa:шато-тамань-125-мл','bar','ckwsbynkaa','Игристые вина','Шато Тамань 125 мл.','','',400,'/menu-images/product-ckwsbynkaa-kusnhkf-qy.webp',true,67),
('bar:ckwsbynkaa:просекко-125-мл','bar','ckwsbynkaa','Игристые вина','Просекко 125 мл.','','',650,'/menu-images/product-ckwsbynkaa-bumnnyfnyi.webp',true,68),
('bar:ckwsbynkaa:просекко-канти','bar','ckwsbynkaa','Игристые вина','Просекко Канти','','200 мл.',900,null,true,69),
('bar:ckwsbynkaa:шато-тамань-750-мл','bar','ckwsbynkaa','Игристые вина','Шато Тамань 750 мл.','','',2400,'/menu-images/product-ckwsbynkaa-vsehnktflq.webp',true,70),
('bar:ckwsbynkaa:просекко-750-мл','bar','ckwsbynkaa','Игристые вина','Просекко 750 мл.','','',3900,'/menu-images/product-ckwsbynkaa-sw-p-bjxnk.webp',true,71),
('bar:ckwsbynkaa:асти-750-мл','bar','ckwsbynkaa','Игристые вина','Асти 750 мл.','','',3000,'/menu-images/product-ckwsbynkaa-lmel-nvxtj.webp',true,72),
('bar:ckwsbynkaa:мартини-асти-d-o-c-g-750-мл','bar','ckwsbynkaa','Игристые вина','Мартини Асти D.O.C.G. 750 мл.','','',4900,'/menu-images/product-ckwsbynkaa-gaeihaljnf.webp',true,73),
('bar:vabrnaxbka:дюарс-уайт-лэйбл-50-мл','bar','vabrnaxbka','Виски','Дюарс Уайт Лэйбл 50 мл.','','',500,'/menu-images/product-vabrnaxbka-lcggvintly.webp',true,74),
('bar:vabrnaxbka:гленгэрри-50-мл','bar','vabrnaxbka','Виски','Гленгэрри 50 мл.','','',350,'/menu-images/product-vabrnaxbka-dlasv-lwxf.webp',true,75),
('bar:vabrnaxbka:бушмилс-50-мл','bar','vabrnaxbka','Виски','Бушмилс 50 мл.','','',450,'/menu-images/product-vabrnaxbka-lkkvcgtyfr.webp',true,76),
('bar:vabrnaxbka:чивас-ригал-50-мл','bar','vabrnaxbka','Виски','Чивас Ригал 50 мл.','','',700,'/menu-images/product-vabrnaxbka-hhzoxbtabe.webp',true,77),
('bar:vabrnaxbka:джек-дэниэлс-50-мл','bar','vabrnaxbka','Виски','Джек Дэниэлс 50 мл.','','',600,'/menu-images/product-vabrnaxbka-svzvurzwyi.webp',true,78),
('bar:pc-mfaoysx:мамонт-50-мл','bar','pc-mfaoysx','Водка','Мамонт 50 мл.','','',300,'/menu-images/product-pc-mfaoysx-efacfdkclt.webp',true,79),
('bar:pc-mfaoysx:финляндия-50-мл','bar','pc-mfaoysx','Водка','Финляндия 50 мл.','','',400,'/menu-images/product-pc-mfaoysx-kmidhqmozd.webp',true,80),
('bar:unwppmnaty:онегин-вишня-50-мл','bar','unwppmnaty','Настойки','Онегин вишня 50 мл.','','',250,'/menu-images/product-unwppmnaty-u-rrdgbttz.webp',true,81),
('bar:unwppmnaty:онегин-курага-50-мл','bar','unwppmnaty','Настойки','Онегин курага 50 мл.','','',250,'/menu-images/product-unwppmnaty-vcmaydrkvz.webp',true,82),
('bar:unwppmnaty:онегин-грейпфрут-50-мл','bar','unwppmnaty','Настойки','Онегин грейпфрут 50 мл.','','',250,'/menu-images/product-unwppmnaty-hrblcxfamf.webp',true,83),
('bar:unwppmnaty:онегин-черная-смородина-50-мл','bar','unwppmnaty','Настойки','Онегин черная смородина 50 мл.','','',250,'/menu-images/product-unwppmnaty-buioayobdk.webp',true,84),
('bar:unwppmnaty:онегин-черноплодная-рябина-50-мл','bar','unwppmnaty','Настойки','Онегин черноплодная рябина 50 мл.','','',250,'/menu-images/product-unwppmnaty-ouhzcxzq-c.webp',true,85),
('bar:oddjbxha-b:арарат-3-50-мл','bar','oddjbxha-b','Коньяк','Арарат 3* 50 мл.','','',350,'/menu-images/product-oddjbxha-b-jtehocbwjv.webp',true,86),
('bar:oddjbxha-b:хеннесси-vs-50-мл','bar','oddjbxha-b','Коньяк','Хеннесси VS 50 мл.','','',900,'/menu-images/product-oddjbxha-b-buyfmepwox.webp',true,87),
('bar:huvdrclwbz:кампо-азул-silver-50-мл','bar','huvdrclwbz','Текила','Кампо Азул silver 50 мл.','','',450,null,true,88),
('bar:huvdrclwbz:де-лос-дорадос-silver-50-мл','bar','huvdrclwbz','Текила','Де Лос Дорадос silver 50 мл.','','',550,null,true,89),
('bar:huvdrclwbz:хосе-куэрво-silver-50-мл','bar','huvdrclwbz','Текила','Хосе Куэрво silver 50 мл.','','',600,null,true,90),
('bar:whyrjhpgtm:оакхарт-ориджинал-50-мл','bar','whyrjhpgtm','Ром','Оакхарт Ориджинал 50 мл.','','',600,null,true,91),
('bar:whyrjhpgtm:такамака-бланк-50-мл','bar','whyrjhpgtm','Ром','Такамака Бланк 50 мл.','','',350,null,true,92),
('bar:whyrjhpgtm:такамака-дарк-50-мл','bar','whyrjhpgtm','Ром','Такамака Дарк 50 мл.','','',350,null,true,93),
('bar:whyrjhpgtm:капитан-морган-темный-50-мл','bar','whyrjhpgtm','Ром','Капитан Морган темный 50 мл.','','',400,null,true,94),
('bar:g-e-wegcug:би-джин-50-мл','bar','g-e-wegcug','Джин','Би Джин 50 мл.','','',200,null,true,95),
('bar:g-e-wegcug:бифитер-50-мл','bar','g-e-wegcug','Джин','Бифитер 50 мл.','','',550,null,true,96),
('bar:lvbnegxo-i:фернет-бранка-50-мл','bar','lvbnegxo-i','Биттер','Фернет - Бранка 50 мл.','','',600,null,true,97),
('bar:lvbnegxo-i:ягермайстер-50-мл','bar','lvbnegxo-i','Биттер','Ягермайстер 50 мл.','','',500,null,true,98),
('bar:vtmh-rtiff:мартини-фиеро-50-мл','bar','vtmh-rtiff','Вермут','Мартини Фиеро 50 мл.','','',400,null,true,99),
('bar:vtmh-rtiff:мартини-бьянко-50-мл','bar','vtmh-rtiff','Вермут','Мартини Бьянко 50 мл.','','',400,null,true,100),
('bar:vtmh-rtiff:мартини-россо-50-мл','bar','vtmh-rtiff','Вермут','Мартини Россо 50 мл.','','',400,null,true,101),
('bar:euazcndqwm:мартини-фиеро-тоник','bar','euazcndqwm','Коктейли','Мартини Фиеро - Тоник','','',900,null,true,102),
('bar:euazcndqwm:май-тай','bar','euazcndqwm','Коктейли','Май Тай','','',900,null,true,103),
('bar:euazcndqwm:негрони','bar','euazcndqwm','Коктейли','Негрони','','',900,null,true,104),
('bar:euazcndqwm:лонг-айленд','bar','euazcndqwm','Коктейли','Лонг Айленд','','',900,null,true,105),
('bar:euazcndqwm:апероль-спритц','bar','euazcndqwm','Коктейли','Апероль Спритц','','',900,null,true,106),
('bar:euazcndqwm:беллини','bar','euazcndqwm','Коктейли','Беллини','','',900,null,true,107),
('bar:euazcndqwm:россини','bar','euazcndqwm','Коктейли','Россини','','',900,null,true,108),
('bar:euazcndqwm:гимлет-бузина','bar','euazcndqwm','Коктейли','Гимлет-бузина','','',900,null,true,109),
('bar:euazcndqwm:лост-френд','bar','euazcndqwm','Коктейли','Лост Френд','','',900,null,true,110),
('bar:euazcndqwm:порн-стар','bar','euazcndqwm','Коктейли','Порн Стар','','',900,null,true,111),
('bar:futdsvldkq:фисташки','bar','futdsvldkq','Закуски','Фисташки','','',400,null,true,112),
('bar:futdsvldkq:арахис','bar','futdsvldkq','Закуски','Арахис','','',300,null,true,113),
('bar:futdsvldkq:чипсы-в-ассортименте','bar','futdsvldkq','Закуски','Чипсы в ассортименте','','',250,null,true,114),
('bar:futdsvldkq:мясо-курицы','bar','futdsvldkq','Закуски','Мясо курицы','','',500,null,true,115),
('bar:futdsvldkq:мясо-говядины','bar','futdsvldkq','Закуски','Мясо говядины','','',550,null,true,116),
('bar:futdsvldkq:мясо-оленя','bar','futdsvldkq','Закуски','Мясо оленя','','',550,null,true,117),
('bar:bifsxyjojt:мясная','bar','bifsxyjojt','Пицца','Мясная','','',900,null,true,118),
('bar:bifsxyjojt:ветчина-и-грибы','bar','bifsxyjojt','Пицца','Ветчина и грибы','','',900,null,true,119),
('bar:bifsxyjojt:пепперони','bar','bifsxyjojt','Пицца','Пепперони','','',900,null,true,120),
('bar:bifsxyjojt:четыре-сыра','bar','bifsxyjojt','Пицца','Четыре сыра','','',900,null,true,121),
('bar:hijuf-uq-n:мороженое','bar','hijuf-uq-n','Десерты','Мороженое','','',300,null,true,122),
('bar:hijuf-uq-n:печенье','bar','hijuf-uq-n','Десерты','Печенье','','',350,null,true,123),
('bar:hijuf-uq-n:шоколадки','bar','hijuf-uq-n','Десерты','Шоколадки','','',350,null,true,124),
('hookah:hookah:классический-кальян','hookah','hookah','Кальяны','Классический кальян','Традиционная подача и мягкий, сбалансированный вкус.','',2150,null,true,125),
('hookah:hookah:на-грейпфруте','hookah','hookah','Кальяны','На грейпфруте','Сочная цитрусовая подача с более ярким ароматом.','',2600,null,true,126),
('hookah:hookah:авторский','hookah','hookah','Кальяны','Авторский','Фирменное сочетание вкусов и особая подача от мастера.','',2800,null,true,127),
('hookah:hookah:электронная-чаша','hookah','hookah','Кальяны','Электронная чаша','Современный нагрев, стабильный вкус и чистая подача.','',3000,null,true,128),
('hookah:hookah:эксклюзивный','hookah','hookah','Кальяны','Эксклюзивный','Премиальная подача, редкие сочетания и максимум внимания к деталям.','',3500,null,true,129),
('hookah:hookah:добавка-премиум-табаков','hookah','hookah','Кальяны','Добавка премиум табаков','Дополнение к выбранному кальяну премиальными линейками табака.','',450,null,true,130)
on conflict (item_key) do update set name=excluded.name, description=excluded.description, volume=excluded.volume, price=excluded.price, image_url=excluded.image_url, sort_order=excluded.sort_order;
